mywallet/accounts/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name':'login.html'}, name='login'),
    url(r'^logout/', 'django.contrib.auth.views.logout', {'next_page':'accounts:login'}, name='logout'),
    url(r'^signup/$', 'mywallet.accounts.views.signup', name='signup'),
    url(r'^preferences/$', 'mywallet.accounts.views.preferences', name='preferences'),
)

mywallet/core/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('mywallet.core.views',
    url(r'^$', 'index', name='index'),
    url(r'^home/$', 'home', name='home'),
    url(r'^about/$', 'about', name='about'),
    url(r'^contact/$', 'contact', name='contact'),
    url(r'^donate/$', 'donate', name='donate'),
    url(r'^bill/(?P<pk>\d+)/$', 'bill', name='bill'),
)

mywallet/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('mywallet.core.urls', namespace='core')),
    url(r'^accounts/', include('mywallet.accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
)

mywallet/accounts/models.py
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin, UserManager)
from django.core import validators
import re


class User(AbstractBaseUser, PermissionsMixin):
    name = models.CharField('Name', max_length=200)
    email = models.EmailField('Email', max_length=150, unique=True)
    username = models.CharField(
        'Username', max_length=30, unique=True,
        validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'),
                                              'Username can only contain letters, digits or the following characters: @/./+/-/_',
                                              'invalid')]
    )

    is_active = models.BooleanField('Is active?', blank=True, default=False)
    is_staff = models.BooleanField('Is admin?', blank=True, default=False)

    date_joined = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return self.name

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

mywallet/bills/models.py
from django.db import models
from mywallet.accounts.models import User


class Bill(models.Model):
    TYPE_CHOICES = (
        ('expense', 'Expense'),
        ('revenue', 'Revenue')
    )

    name = models.CharField('Name', max_length=200)
    value = models.DecimalField('Value', max_digits=8, decimal_places=2)
    bill_type = models.CharField(
        'Type', max_length=8, choices=TYPE_CHOICES,
        default='revenue'
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(User)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Bill'
        verbose_name_plural = 'Bills'

mywallet/core/models.py
from django.db import models

# Create your models here.

mywallet/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password Confirmation', widget=forms.PasswordInput
    )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Password confirmation is not valid!')
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['name', 'email', 'username']

mywallet/bills/forms.py
from django import forms
from .models import Bill


class BillForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(BillForm, self).__init__(*args, **kwargs)
        self.user = user

    def save(self, commit=True):
        bill = super(BillForm, self).save(commit=False)
        bill.user = self.user
        if commit:
            bill.save()
        return bill

    class Meta:
        model = Bill
        fields = ['name', 'value', 'bill_type']

mywallet/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import RegisterForm


def signup(request):
    template_name = 'signup.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username,
                password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('core:home')
    else:
        form = RegisterForm()

    context = {
        'form': form
    }

    return render(request, template_name, context)


def preferences(request):
    return render(request, 'preferences.html')

mywallet/bills/views.py
from django.shortcuts import render

# Create your views here.

mywallet/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from mywallet.bills.models import Bill
from mywallet.bills.forms import BillForm
from mywallet.accounts.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    return render(request, 'index.html')


@login_required
def home(request):
    user = request.user
    bills = Bill.objects.filter(user=user)
    form = BillForm(user)
    total = 0
    for bill in bills:
        if bill.bill_type == 'revenue':
            total += bill.value
        else:
            total -= bill.value

    # Django pagination
    paginator = Paginator(bills, 5)
    page = request.GET.get('page')
    try:
        bills = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        bills = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        bills = paginator.page(paginator.num_pages)

    context = {
        'form': form,
        'bills': bills,
        'total': total
    }

    return render(request, 'home.html', context)


def bill(request, pk):
    user = User.objects.get(pk=pk)
    if request.method == 'POST':
        form = BillForm(user=user, data=request.POST)
        if form.is_valid():
            form.save()

    return redirect('core:home')


def about(request):
    return render(request, 'about.html')


def contact(request):
    return render(request, 'contact.html')


def donate(request):
    return render(request, 'donate.html')

mywallet/accounts/templates/login.html
<!doctype html>
{% load static %}
<html>
<head>
    <title>MyWallet - Login</title>
    <meta charset="UTF-8">
    <link rel="icon" type="image/ico" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/foundation.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}"/>

    <script type="text/javascript" src="{% static 'js/vendor/modernizr.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/placeholder.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/fastclick.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/foundation.min.js' %}"></script>

</head>
<body>
<div class="div-center">
    <fieldset>
        <legend>Sign In</legend>
        <div class="row">
            <form data-abide method="POST">
                {% csrf_token %}
                <div class="login-field">
                    <label>Login
                        <small>required</small>
                        {{ form.username }}
                    </label>
                    <small class="error">Login is required.</small>
                </div>
                <div class="password-field">
                    <label for="password">Password
                        <small>required</small>
                        {{ form.password }}
                    </label>
                    <small class="error">Password is required.</small>
                </div>
                <a href="{% url 'accounts:signup' %}">Sign Up</a>
                <hr/>
                <button type="submit">Sign In</button>
            </form>
        </div>
    </fieldset>

    <br/><br/>

    <div id="footer">
        <center><p style="font-size: 10px;">Developed by <a
                href="https://github.com/marquesds" target="blank">Lucas Marques</a></p>
        </center>
    </div>

</div>

<script>
	$(document).foundation();
</script>
</body>
</html>

mywallet/accounts/templates/preferences.html
{% extends "base.html" %}

{% block title %}Preferences{% endblock %}

{% block content %}
    <center><h1>Here you can set your account preferences.</h1></center>
    <center><h3>If I develop this feature, of course.</h3></center>
{% endblock %}

mywallet/accounts/templates/signup.html
<!doctype html>
{% load static %}
<html>
<head>
    <title>Finice - Login</title>
    <meta charset="UTF-8">
    <link rel="icon" type="image/ico" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/foundation.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}"/>


</head>
<body>
<div class="div-center">
    <fieldset>
        <legend>Sign Up</legend>
        <div class="row">
            <form data-abide method="POST">
                {% csrf_token %}
                <div class="name-field">
                    <label>Name
                        <small>required</small>
                        {{ form.name }}
                    </label>
                    <small class="error">Name is required.</small>
                </div>
                <div class="name-field">
                    <label>Username
                        <small>required</small>
                        {{ form.username }}
                    </label>
                    <small class="error">Name is required.</small>
                </div>
                <div class="email-field">
                    <label>Email
                        <small>required</small>
                        {{ form.email }}
                    </label>
                    <small class="error">Email is required.</small>
                </div>
                <div class="password-field">
                    <label for="password">Password
                        <small>required</small>
                        {{ form.password1 }}
                    </label>
                    <small class="error">Password is required.</small>
                </div>
                <div class="password-field">
                    <label for="password">Password Confirmation
                        <small>required</small>
                        {{ form.password2 }}
                    </label>
                    <small class="error">Password Confirmation is wrong.</small>
                </div>
                <a href="{% url 'accounts:login' %}">Already have an account?</a>
                <hr/>
                <button type="submit">Sign Up</button>
            </form>
        </div>
    </fieldset>

    <br/><br/>

    <div id="footer">
        <center><p style="font-size: 10px;">Developed by <a
                href="https://github.com/marquesds" target="blank">Lucas Marques</a></p>
        </center>
    </div>

</div>
<script>
	$(document).foundation();
</script>
</body>
</html>

mywallet/core/templates/about.html
{% extends "base.html" %}

{% block title %}About{% endblock %}

{% block content %}
<center><h1>Lorem Ipsum, Lorem Ipsum Everywhere!</h1></center>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore
    magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis
    nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse
    molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui
    blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta
    nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent
    claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores
    legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium
    lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas
    humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant
    sollemnes in futurum.</p>

<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore
    magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis
    nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse
    molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui
    blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta
    nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent
    claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores
    legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium
    lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas
    humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant
    sollemnes in futurum.</p>

<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore
    magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis
    nisl ut aliquip ex ea commodo consequat.</p>
{% endblock %}

mywallet/core/templates/base.html
<!doctype html>
{% load static %}
<html>
<head>
    <title>My Wallet - {% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <link rel="icon" type="image/ico" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}"/>
    <script type="text/javascript" src="{% static 'js/vendor/modernizr.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/placeholder.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/fastclick.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/foundation.min.js' %}"></script>
</head>
<body>
<div class="page">
    <div class="off-canvas-wrap" data-offcanvas>
        <div class="inner-wrap">
            <nav class="tab-bar">
                <section class="left-small">
                    <a class="left-off-canvas-toggle menu-icon"><span></span></a>
                </section>

                <section class="middle tab-bar-section">
                    <h1 class="title"><a href="{% url 'core:home' %}"><img src="{% static 'img/wallet.png' %}" class="home-image"> My Wallet</a></h1>
                </section>
            </nav>

            <aside class="left-off-canvas-menu">
                <form data-abide method='POST'>
                    {% csrf_token %}
                    <ul class="off-canvas-list">
                        <li><label>My Wallet</label></li>
                        <li><a href="{% url 'core:home' %}">Home</a></li>
                        <li><a href="{% url 'core:about' %}">About</a></li>
                        <li><a href="{% url 'core:contact' %}">Contact</a></li>
                        <li><a href="{% url 'core:donate' %}">Donate</a></li>
                        <li><label>System</label></li>
                        <li><a href="{% url 'accounts:preferences' %}">Preferences</a></li>
                        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    </ul>
                </form>
            </aside>

            {% block content %}{% endblock %}

            <div id="footer">
                <center><p style="font-size: 10px;">Developed by <a
                        href="https://github.com/marquesds" target="blank">Lucas Marques</a></p>
                </center>
            </div>
        <a class="exit-off-canvas"></a>
        </div>
    </div>
</div>
<script>
	$(document).foundation();

</script>
</body>
</html>

mywallet/core/templates/contact.html
{% extends "base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}
    <center><h1>If you found a bug, please keep secret!</h1></center>
    <center><h3>PS.: There is no bug here, everything is a feature!</h3></center>
{% endblock %}

mywallet/core/templates/donate.html
{% extends "base.html" %}

{% block title %}Donate :D{% endblock %}

{% block content %}
<center><h1>And here is the coolest page ever!</h1></center>
<center><h3>Shame that not yet developed :'(</h3></center>
{% endblock %}

mywallet/core/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<section class="main-section">
    <br/>
    {% if user.is_authenticated %}
    <small class="welcome">Welcome, <a href="{% url 'accounts:preferences' %}">{{ user.name }}</a>!</small>
    {% endif %}
    <div class="row">
        <div class="large-12 columns">
            <br/><br/><br/>
            <a href="#" class="button small radius round" data-reveal-id="myModal">Add</a>
            <table>
                <thead>
                <tr>
                    <th width="250">Name</th>
                    <th width="250">Type</th>
                    <th width="250">Date</th>
                    <th width="250">Value</th>
                </tr>
                </thead>
                <tbody>
                {% for bill in bills %}
                <tr>
                    <td>{{ bill.name }}</td>
                    <td>{{ bill.bill_type }}</td>
                    <td>{{ bill.created_at }}</td>
                    <td class="{% if bill.bill_type == 'revenue' %}revenue{% elif bill.bill_type == 'expense' %}expense{% endif %}">
                        ${{ bill.value }}
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td>----------</td>
                    <td>----------</td>
                    <td>----------</td>
                    <td>----------</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="pagination-centered">
                <ul class="pagination">
                    {% if bills.has_previous %}
                      <li><a href="?page={{ bills.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                      <li class="disabled"><a href="#">&laquo;</a></li>
                    {% endif %}

                    {% for num in bills.paginator.page_range %}
                        {% ifequal num bills.number %}
                            <li class="current"><a href="">{{ num }}</a></li>
                        {% else %}
                            <li><a href="?page={{ num }}">{{ num }}</a></li>
                        {% endifequal %}
                    {% endfor %}

                    {% if bills.has_next %}
                      <li><a href="?page={{ bills.next_page_number }}">&raquo;</a></li>
                    {% else %}
                      <li class="disabled"><a href="#">&raquo;</a></li>
                    {% endif %}
                </ul>
            </div>
            <small>Total: <b class="{% if total > 0 %}revenue{% elif total < 0 %}expense{% endif %}">${{ total }}</b>
            </small>
            <hr/>
        </div>
    </div>
</section>
<div id="myModal" class="reveal-modal" data-reveal>
    <h2>Add new entry</h2>
    <fieldset>
        <form action="/bill/{{ user.id }}/" data-abide method="POST">
            {% csrf_token %}
            <div class="name-field">
                <label for="id_name">Name
                    <small>required</small>
                    {{ form.name }}
                </label>
                <small class="error">Name is required and must be a string.</small>
            </div>
            <div class="row collapse">
                <label for="id_bill_type">Type
                    <small>required</small>
                    {{ form.bill_type }}
                </label>
                <small class="error">Type is required.</small>
            </div>
            <br/>

            <div class="row">
                <div class="number-field large-3">
                    <label for="id_value">Value ($)
                        <small>required</small>
                        {{ form.value }}
                    </label>
                    <small class="error">Value is required.</small>
                </div>
            </div>
            <hr/>
            <button type="submit">Submit</button>
        </form>
    </fieldset>
    <a class="close-reveal-modal">&#215;</a>
</div>
{% endblock %}

mywallet/core/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>My Wallet</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/business-frontpage.css' %}" rel="stylesheet">

    <link rel="icon" type="image/ico" href="{% static 'img/favicon.ico' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
<a href="https://github.com/marquesds/mywallet" target="_blank"><img
        style="position: absolute; top: 0; right: 0; border: 0; z-index: 1040; position: fixed;"
        src="https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67"
        alt="Fork me on GitHub"
        data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"></a>
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'core:index' %}">My Wallet</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#about">About</a>
                </li>
                <li>
                    <a href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li>
                    <a href="{% url 'accounts:signup' %}">Signup</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Image Background Page Header -->
<!-- Note: The background image is set within the business-casual.css file. -->
<header class="business-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="tagline">Welcome to My Wallet!</h1>
            </div>
        </div>
    </div>
</header>

<!-- Page Content -->
<div class="container" id="about">

    <hr>

    <div class="row">
        <div class="col-sm-8">
            <h2>How it works?</h2>

            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
                deserunt mollit anim id est laborum.</p>

            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et molestiae similique eligendi reiciendis sunt
                distinctio odit? Quia, neque, ipsa, adipisci quisquam ullam deserunt accusantium illo iste
                exercitationem nemo voluptates asperiores.</p>

            <p>
                <a class="btn btn-primary btn-lg" href="{% url 'accounts:signup' %}">Signup &raquo;</a>
            </p>
        </div>
        <div class="col-sm-4">
            <h2>Contact <strike><i>Us</i></strike> Me</h2>
            <address>
                <strong><a href="https://github.com/marquesds" target="_blank">Lucas Marques</a></strong>
                <br>São Carlos - SP
                <br>
            </address>
            <address>
                <abbr title="Phone">Phone: </abbr>(16) 98136-2670
                <br>
                <abbr title="Email">Email: </abbr> <a href="mailto:#">lucasmarquesds@gmail.com</a>
            </address>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; My Wallet 2014</p>
            </div>
        </div>
        <!-- /.row -->
    </footer>

</div>
<!-- /.container -->

<!-- jQuery Version 1.11.0 -->
<script src="{% static 'js/vendor/jquery.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/vendor/jquery.easing.pack.js' %}"></script>

<script type="text/javascript">
    $(function() {
        $('#more a, a, .navbar-brand a, .navbar-toggle a, .navbar a, .nav a, .nav li a, .brand, #footer li a').bind('click',function(event){
        var $anchor = $(this);

        $('[data-spy="scroll"]').each(function () {
        var $spy = $(this).scrollspy('refresh')
        });

        $('html, body').stop().animate({
        scrollTop: $($anchor.attr('href')).offset().top -61
        }, 1500,'easeInOutExpo');

        event.preventDefault();
        });
    });
    </script>


</body>

</html>